#!/bin/sh

# get our asses in here
OURSELVES="`realpath "$0"`"
cd "`dirname "$OURSELVES"`"

# compile the code if we need to
if ! make; then
	printf "Error compiling application\n" >&2
	exit 1
fi

# get our basedir setup
if [ -z "$BASEDIR" ]; then
	BASEDIR="$HOME/.imglib"
	export BASEDIR
fi

# install the app if we need to
if [ ! -d "$BASEDIR" ]; then
	echo "Installing software"
	if ! luvit -e "require './app/install'"; then
		echo "Installation failed" 1>&2
		exit 1
	fi
	echo "Installed software"
fi

# start the daemon
echo "Starting daemon"
exec daemonize/daemonize luvit . 0</dev/null 1>>"$BASEDIR/logfile" 2>&1
