#!/bin/sh

# get our asses in here
OURSELVES="`realpath "$0"`"
cd "`dirname "$OURSELVES"`"

# compile the code if we need to
if ! make; then
	printf "Error compiling application\n" >&2
	exit 1
fi

# get our basedir setup
if [ -z "$BASEDIR" ]; then
	BASEDIR="$HOME/.imglib"
	export BASEDIR
fi

# start the daemon
echo "Starting daemon"
touch "$BASEDIR/logfile"
chmod 600 "$BASEDIR/logfile"
exec daemonize/daemonize luvit . 0</dev/null 1>>"$BASEDIR/logfile" 2>&1
